# https://github.com/drduh/config/blob/master/dnscrypt-proxy.toml
#user_name = '_dnscrypt-proxy'
listen_addresses = ['127.0.0.1:4200']
server_names = ['abc']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
block_ipv6 = true
force_tcp = false
timeout = 2000
keepalive = 60
cert_refresh_delay = 240
tls_cipher_suite = [52393]
fallback_resolver = '0.0.0.0:53'
ignore_system_dns = false
netprobe_timeout = 30
cache = true
cache_size = 1000
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
log_level = 2
log_file = 'dnscrypt.log'
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
forwarding_rules = 'forwarding-rules.txt'
[query_log]
  file = 'query.log'
  format = 'tsv'
[nx_log]
  file = 'nx.log'
  format = 'tsv'
[blacklist]
  blacklist_file = 'blacklist.txt'
  log_file = 'blocked.log'
  log_format = 'tsv'
[ip_blacklist]
  blacklist_file = 'ip-blacklist.txt'
  log_file = 'ip-blocked.log'
  log_format = 'tsv'
[static]
  [static.'abc']
  stamp = 'sdns://AAAAA...'
